
services:
  cci-website:
    build:
      dockerfile: ./Dockerfile
      context: .
      # target: run
    container_name: cci-website
    user: hugo
    restart: always
    ports:
    - 1313:1313
    volumes:
    - .:/www
  
networks:
  cci-website:
    driver: default
